--- thesis/Makefile	2014-04-22 14:49:46.000000000 +0200
+++ thesis/Makefile	2017-01-24 11:58:57.073216409 +0100
@@ -199,7 +199,7 @@
 latexpkg = $(call checking,LaTeX package $(1));	$(TEXENV) kpsewhich '$(1).sty' || { echo 'NOT FOUND! $(2)'; false; };
 latexcls = $(call checking,LaTeX class $(1));	$(TEXENV) kpsewhich '$(1).cls' || { echo 'NOT FOUND! $(2)'; false; };
 
-SHELL_CMDS += bash make mkdir rm false true $(sed) sort find latexmk git wget printf gawk tex pdflatex kpsewhich g++ $(readlink) tee pdftotext date pwd echo uname convert texhash updmap gnuplot gs fmtutil basename md5sum
+SHELL_CMDS += bash make mkdir rm false true $(sed) sort find latexmk git wget printf gawk tex pdflatex kpsewhich g++ $(readlink) tee pdftotext date pwd echo uname convert texhash updmap gnuplot gs fmtutil basename md5sum unzip
 USED_PKGS := $(shell find src texmf/tex/latex -path texmf/tex/latex/acrotex/doc -prune -o \( -iname '*.tex' -o -iname '*.cls' -o -iname '*.sty' \) -exec \
 	grep -i '^[ \t]*\\\(usepackage\|RequirePackage\).*{' {} \; | \
 	$(sed) 's/^[^{[]*\(\[[^]]*\]\)\?{\([^}]*\)}.*$$/\2/;s/,/\n/g' 2>/dev/null | \
@@ -245,7 +245,14 @@
 	@$(TEXENV) texhash texmf
 	@$(TEXENV) updmap
 
-acrotex:
+conv-xkv:
+	mkdir -p texmf/tex/latex
+	cd texmf/tex/latex && wget http://mirrors.ctan.org/macros/latex/contrib/conv-xkv.zip
+	cd texmf/tex/latex && unzip conv-xkv.zip
+	cd texmf/tex/latex/conv-xkv && latex conv-xkv.ins
+	rm texmf/tex/latex/conv-xkv.zip
+	
+acrotex: conv-xkv
 	mkdir -p texmf/tex/latex
 	cd texmf/tex/latex && wget http://mirrors.ctan.org/macros/latex/contrib/acrotex.zip
 	cd texmf/tex/latex && unzip acrotex.zip
@@ -270,7 +277,7 @@
 
 font-%: | texmf/FontPro
 	cd texmf/FontPro && scripts/makeall $* --nocyrillic --novietnamese --expanded
-	i="`$(readlink) -f texmf`"; cd texmf/FontPro && scripts/install "$$i"
+	i="`$(readlink) -f texmf`"; cd texmf/FontPro && scripts/install "$$i" <<< 'y'
 	cd texmf/FontPro && scripts/clean
 	$(TEXENV) cd texmf && updmap --enable Map=$*.map
 	@$(BUILD_TIME)
